version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - sudo curl -fLSs https://circle.ci/cli | bash
  build:
    commands:
      - echo "Setting Token"
      - chmod +x setup-token.sh
      - ./setup-token.sh
      - circleci orb validate katalon-orb.yml