version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - curl -fLSs https://circle.ci/cli | bash
  build:
    commands:
      - printenv
      - echo "Setting Token"
      - chmod +x setup-token.sh
      - ./setup-token.sh
      - cat ~/.circleci/cli.yml 
      - echo "Validate the syntax structure"
      - circleci orb validate katalon-orb.yml
      - echo "Verify before publish"
      - circleci orb process katalon-orb.yml
      - echo Testing with sample circleci  which using orb
      - circleci config process .circleci/config.yml

  post_build:
    commands:
      - circleci orb publish increment katalon-orb.yml katalon/katalon-studio patch
