version: 2.1
description: >
 Execute Katalon tests with your CircleCI CI/CD pipeline easily with the Katalon orb
display:
  home_url: https://docs.katalon.com/katalon-studio/docs/integration-circleci.html
  source_url: https://github.com/katalon-studio/katalon-circleci-orb
  api_url: https://docs.katalon.com/katalon-analytics/docs/ka-api-key.html
orbs:
examples:
  execute_test:
    description: Executing a test suite named TS_RegressionTest with the latest Katalon Studio version
    usage:
      version: 2.1
      orbs:
        katalonstudio: katalon/katalonstudio@12.0.0
      environment:
        API_KEY: $API_KEY
      workflows:
       build:
        jobs:
            - katalonstudio/test:
                    version: "latest"
                    command: "-browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/TS_RegressionTest'"

executors:
      default:
        description: Ubuntu based Docker Image for Katalon Studio
        parameters:
          version:
            type: string
            default: "latest"
            description : "Only Katalon Studio 7+ supported"
        docker:
          - image: katalonstudio/katalon:<<parameters.version>>
commands:
      command_execute_test:
        description:  Defining command arguments to execute your Katalon tests with API Key required
        parameters:
          COMMAND_ARGUMENTS:
            type: string
            default: ""
            description: The defined command arguments used for executing your Katalon tests
          API_KEY:
            type: string
            default: ""
            description: The API KEY used for authentication with Katalon Server
        steps:
          - run: katalon-execute.sh -apiKey=<<parameters.API_KEY>> <<parameters.COMMAND_ARGUMENTS>> 
jobs:
      test:
          description: Executing your Katalon tests with the defined command arguments in the Docker Image for Katalon Studio
          executor: default
          parameters:
            version:
              default: "latest"
              type: string
              description:  default is latest Katalon studio version
            API_KEY:
              type: env_var_name
              default: API_KEY
              description: The API KEY used for authentication with Katalon Server. Learn [how to get the API KEY](https://docs.katalon.com/katalon-analytics/docs/ka-api-key.html).
            COMMAND_ARGUMENTS:
              default: ""
              type: string
              description: The defined command arguments used for executing your Katalon tests. See [Command Syntax](https://docs.katalon.com/katalon-studio/docs/console-mode-execution.html).

          steps:
            - checkout
            - run:
                command: |-
                  ls -la
            - command_execute_test:
                API_KEY: ${API_KEY}
                COMMAND_ARGUMENTS: <<parameters.COMMAND_ARGUMENTS>>
            - store_artifacts:
                  path: report
workflows:
  build:
    jobs:
        - katalonstudio/test:
            executor: katalonstudio/default
            steps:
                    - checkkout
                    - katalonstudio/command_execute_test:
                        version: "latest"
                        command_execute_test: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
                        