version: 2.1
description: For easy to Run katalon studio test using cirlce-ci 
display:
  home_url: https://docs.katalon.com/katalon-studio/docs/integration-circleci.html
  source_url: https://github.com/katalon-studio/katalon-circleci-orb
orbs:
  
examples:
  katalon_users:
    description: This is the example to use katalon studio orbs ,Push your testcase code and change your katalon version and your parameter and api key to test
    usage:
      version: 2.1
      orbs:
        katalonstudio: katalon/katalonstudio@12.0.0
      environment:
        KATALON_API_KEY: $KATALON_API_KEY
      workflows:
       build:
        jobs:
            - katalonstudio/test:
                    version: "latest"
                    ks_param: "-browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/TS_RegressionTest'"

executors:
      katalon_orb_executor:
        description: Ubuntu based docker katalon studio app
        parameters:
          version:
            type: string
            default: "latest"
            description : "katalon version > 7.0"
        docker:
          - image: katalonstudio/katalon:<<parameters.version>>
commands:
      ks_command:
        description:  Define structure of katalon command with 2 parts API Key and katalo parameter
        parameters:
          ks_param:
            type: string
            default: ''
            description: this string is used for Katjob Job 
          ks_api_key:
            type: string
            default: ""
            description: This is used for katjob, katjob is need to set environment variables in your circleci 
        steps:
          - run: katalon-execute.sh -apiKey=<<parameters.ks_api_key>> <<parameters.ks_param>> 
jobs:
      test:
          description: Katalon CI/CD job to run katalon command in environment katalon executor 
          executor: katalon_orb_executor
          parameters:
            version:
              default: "latest"
              type: string
              description:  default is latest Katalon studio version
            ks_api_key:
              type: env_var_name
              default: KATALON_API_KEY
              description: get api-key from https://analytics.katalon.com/ ,document from https://docs.katalon.com/katalon-store/docs/user/API-key.html#api-keys-usage
            ks_param:
              default: ""
              type: string
              description: Reference from console https://docs.katalon.com/katalon-studio/docs/console-mode-execution.html#proxy-options

          steps:
            - checkout
            - run:
                command: |-
                  ls -la
            - ks_command:
                ks_api_key: ${KATALON_API_KEY}
                ks_param: <<parameters.ks_param>>
            - store_artifacts:
                  path: report
workflows:
  build:
    jobs:
        - katalonstudio/test:
            executor: katalonstudio/katalon_orb_executor
            steps:
                    - checkkout
                    - katalonstudio/ks_command:
                        version: "latest"
                        katalon_param: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
                        