version: 2.1
description: Run katalon studio test using cirlce-ci 

orbs:
  codecov: circleci/codecov-clojure@0.0.4

examples:
  katalon_users:
    description: This is the example to use katalon studio orbs 
    usage:
      version: 2.1
      orbs:
        katalonstudio: katalon-orb-test/katalonstudio@0.0.31
      workflows:
       build:
        jobs:
            - katalonstudio/katjob:
                    version: "latest"
                    katalon_param: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'

executors:
      katalon_orb_executor:
        parameters:
          version:
            type: string
            default: "latest"
        docker:
          - image: katalonstudio/katalon:<<parameters.version>>
commands:
      katalon_command:
        parameters:
          katalon_param:
            type: string
            default: ''
        steps:
          - run: katalon-execute.sh <<parameters.katalon_param>>
jobs:
      katjob:
          executor: katalon_orb_executor
          parameters:
            version:
              default: "latest"
              type: string
            katalon_param:
              default: ""
              type: string
          steps:
            - checkout
            - run:
                command: |-
                  ls -la
            - katalon_command:
                katalon_param: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
            - codecov/upload:
                  path: ./report/*
workflows:
  build:
    jobs:
        - katalonstudio/katjob:
            executor: katalonstudio/katalon_orb_executor
            steps:
                    - checkkout
                    - katalonstudio/katalon_command:
                        katalon_param: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'