version: 2.1
description: Run katalon studio test using cirlce-ci 

orbs:
  codecov: circleci/codecov-clojure@0.0.4
executors:
      katalon_orb_executor:
        parameters:
          version:
            type: string
            default: "7.0"
        docker:
          - image: katalonstudio/katalon:<<parameters.version>>
commands:
      katalon_command:
        parameters:
          katalon_param:
            type: string
            default: ''
        steps:
          - run: katalon-execute.sh <<parameters.katalon_param>>
jobs:
      katjob:
          executor: 
            name: katalon_orb_executor
            version: "7.0"
          steps:
            - checkout
            - katalon_command
            - codecov/upload:
                  path: ./report/*
workflows:
  build:
    jobs:
        - katalonstudio/katjob:
            executor: katalonstudio/katalon_orb_executor
            steps:
                    - checkkout
                    - katalonstudio/katalon_command:
                        katalon_param: '-browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'