name: KatalonCircleCIOrb
on:
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: install circleci tool 
      run: |
        curl -fLSs https://circle.ci/cli | DESTDIR=/opt/bin/bash
    - name: Setup token for circleci 
      run: |
        chmod +x setup-token.sh
        ./setup-token.sh
